server:
  port: 8082

spring:
  application:
    name: user-service

    uri: lb://USER-SERVICE

    predicates:

      - Path=/users/**

    filters:

      - name: RequestRateLimiter

        args:

          redis-rate-limiter.replenishRate: 20

          redis-rate-limiter.burstCapacity: 30

          key-resolver: "#{@userKey}"

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/formoura_user
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  kafka:

    bootstrap-servers: localhost:9092

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:

  api-docs:

    enabled: true

    path: /v3/api-docs

  swagger-ui:

    enabled: true

    path: /swagger-ui.html

    display-request-duration: true

    operations-sorter: method

    tags-sorter: alpha

    try-it-out-enabled: true

aws:
  access-key: YOUR_ACCESS_KEY
  secret-key: YOUR_SECRET_KEY
  region: ap-south-1
  bucket-name: formoura-images

jwt:
  secret-key: bXktc3VwZXItc2VjcmV0LWtleS1mb3ItZm9ybW91cmEtMjU2LWJpdA==
  access-token-expiration: 900000
  refresh-token-expiration: 604800000