server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/formoura_auth
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: formoura123456789formoura123456789formoura123456789
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka